server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddResponseHeader=X-Gateway, mini-score-api-gateway
          routes:
            - id: core-registry-route
              uri: lb://CORE-REGISTRY-SERVICE
              predicates:
                - Path=/core-registry/**
              filters:
                - StripPrefix=1
            - id: live-engine-route
              uri: lb://LIVE-ENGINE-SERVICE
              predicates:
                - Path=/live-engine/**
              filters:
                - StripPrefix=1
            - id: stats-route
              uri: lb://STATS-SERVICE
              predicates:
                - Path=/stats/**
              filters:
                - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: core-registry-service
        url: /core-registry/api-docs
      - name: live-engine-service
        url: /live-engine/api-docs
      - name: stats-service
        url: /stats/api-docs

management:
  endpoint:
    gateway:
      access: read-only
  endpoints:
    web:
      exposure:
        include: health,info,gateway
