server:
  port: 8080

spring:
  application:
    name: stats-service
  datasource:
    url: jdbc:postgresql://localhost:5433/stats_db
    username: miniscore
    password: miniscore
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    openfeign:
      client:
        config:
          core-registry-service:
            connectTimeout: 1000
            readTimeout: 1500
            loggerLevel: basic

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
