server:
  port: 8080

spring:
  application:
    name: live-engine-service
  mongodb:
    uri: mongodb://localhost:27017/live_engine
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    access:
      default: unrestricted
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
